export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";


export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_SUCCEED = "FETCH_TODOS_SUCCEED";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";


export default {
	FETCH_TODOS_START,
	FETCH_TODOS_SUCCEED,
	FETCH_TODOS_FAIL,
	ADD_TODO,
	REMOVE_TODO,
	COMPLETE_TODO,
};