export const ADD_TODO_START = "ADD_TODO_START";
export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const REMOVE_TODO_START = "REMOVE_TODO_START";
export const COMPLETE_TODO_START = "COMPLETE_TODO_START";

export const ADD_TODO_SUCCEED = "ADD_TODO_SUCCEED";
export const FETCH_TODOS_SUCCEED = "FETCH_TODOS_SUCCEED";
export const REMOVE_TODO_SUCCEED = "REMOVE_TODO_SUCCEED";
export const COMPLETE_TODO_SUCCEED = "COMPLETE_TODO_SUCCEED";

export const ADD_TODO_FAIL = "ADD_TODO_FAIL";
export const FETCH_TODOS_FAIL = "FETCH_TODOS_FAIL";
export const REMOVE_TODO_FAIL = "REMOVE_TODO_FAIL";
export const COMPLETE_TODO_FAIL = "COMPLETE_TODO_FAIL";


export default {
	FETCH_TODOS_START,
	FETCH_TODOS_SUCCEED,
	FETCH_TODOS_FAIL,
	ADD_TODO_START,
	ADD_TODO_SUCCEED,
	ADD_TODO_FAIL,
	REMOVE_TODO_START,
	REMOVE_TODO_SUCCEED,
	REMOVE_TODO_FAIL,
	COMPLETE_TODO_START,
	COMPLETE_TODO_SUCCEED,
	COMPLETE_TODO_FAIL,
};